-- skyline_staging.student_view definition

CREATE TABLE `student_view` (
  `endYear` smallint NOT NULL,
  `districtID` int NOT NULL,
  `calendarID` int NOT NULL,
  `personID` int NOT NULL,
  `structureID` int NOT NULL,
  `noShow` bit(1) NOT NULL,
  `schoolID` int NOT NULL,
  `enrollmentID` int NOT NULL,
  `schoolOfAccountability` int DEFAULT NULL,
  `stateID` varchar(15) DEFAULT NULL,
  `otherID` varchar(15) DEFAULT NULL,
  `additionalID` varchar(25) DEFAULT NULL,
  `edFiID` varchar(20) DEFAULT NULL,
  `studentNumber` varchar(15) DEFAULT NULL,
  `personGUID` varchar(40)  DEFAULT NULL,
  `identityID` int NOT NULL,
  `effectiveDate` timestamp NULL DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `middleName` varchar(50) DEFAULT NULL,
  `suffix` varchar(50) DEFAULT NULL,
  `alias` varchar(50) DEFAULT NULL,
  `gender` char(1) DEFAULT NULL,
  `birthdate` timestamp NULL DEFAULT NULL,
  `ssn` varchar(9) DEFAULT NULL,
  `legalFirstName` varchar(50) DEFAULT NULL,
  `legalLastName` varchar(50) DEFAULT NULL,
  `legalMiddleName` varchar(50) DEFAULT NULL,
  `legalSuffix` varchar(50) DEFAULT NULL,
  `legalGender` char(1) DEFAULT NULL,
  `pronounID` int DEFAULT NULL,
  `raceEthnicity` varchar(3) DEFAULT NULL,
  `hispanicEthnicity` varchar(2) DEFAULT NULL,
  `raceEthnicityFed` varchar(1) DEFAULT NULL,
  `raceEthnicityDetermination` varchar(2) DEFAULT NULL,
  `birthCountry` varchar(4) DEFAULT NULL,
  `birthState` varchar(10) DEFAULT NULL,
  `birthCity` varchar(30) DEFAULT NULL,
  `birthCounty` varchar(30) DEFAULT NULL,
  `homePrimaryLanguage` varchar(5) DEFAULT NULL,
  `languageAlt` varchar(5) DEFAULT NULL,
  `languageAlt2` varchar(5) DEFAULT NULL,
  `languageAlt3` varchar(5) DEFAULT NULL,
  `languageAlt4` varchar(5) DEFAULT NULL,
  `grade` varchar(4) DEFAULT NULL,
  `serviceType` varchar(1) DEFAULT NULL,
  `startDate` timestamp NOT NULL,
  `startStatus` varchar(5) DEFAULT NULL,
  `endDate` timestamp NULL DEFAULT NULL,
  `endStatus` varchar(5) DEFAULT NULL,
  `enrollmentStateExclude` bit(1) NOT NULL,
  `calendarName` varchar(30) DEFAULT NULL,
  `calendarStart` timestamp NULL DEFAULT NULL,
  `calendarEnd` timestamp NULL DEFAULT NULL,
  `calendarExclude` bit(1) NOT NULL,
  `startYear` smallint NOT NULL,
  `label` varchar(10) DEFAULT NULL,
  `activeYear` bit(1) NOT NULL,
  `stateGrade` varchar(4) DEFAULT NULL,
  `gradeLevelExcludeState` bit(1) NOT NULL,
  `gradeLevelExcludeGPA` bit(1) DEFAULT NULL,
  `sifExclude` bit(1) NOT NULL,
  `excludeFromSIF` bit(1) NOT NULL,
  `modifiedDate` timestamp NULL DEFAULT NULL,
  `externalLMSExclude` int NOT NULL,
  `crossSiteEnrollment` bit(1) NOT NULL,
  `immigrant` varchar(2) DEFAULT NULL,
  `refugee` varchar(2) DEFAULT NULL
) ENGINE=InnoDB;







-- skyline_staging.staffMember_view definition

CREATE TABLE `staffMember_view` (
  `personID` int NOT NULL,
  `stateID` varchar(15) DEFAULT NULL,
  `staffNumber` varchar(15) DEFAULT NULL,
  `staffStateID` varchar(20) DEFAULT NULL,
  `identityID` int NOT NULL,
  `effectiveDate` timestamp NULL DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `middleName` varchar(50) DEFAULT NULL,
  `suffix` varchar(50) DEFAULT NULL,
  `alias` varchar(50) DEFAULT NULL,
  `gender` char(1) DEFAULT NULL,
  `birthdate` timestamp NULL DEFAULT NULL,
  `ssn` varchar(9) DEFAULT NULL,
  `legalFirstName` varchar(50) DEFAULT NULL,
  `legalLastName` varchar(50) DEFAULT NULL,
  `legalMiddleName` varchar(50) DEFAULT NULL,
  `legalSuffix` varchar(50) DEFAULT NULL,
  `legalGender` char(1) DEFAULT NULL,
  `raceEthnicity` varchar(3) DEFAULT NULL,
  `employmentID` int DEFAULT NULL,
  `assignmentID` int NOT NULL,
  `startDate` timestamp NULL DEFAULT NULL,
  `endDate` timestamp NULL DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `seniority` varchar(2) DEFAULT NULL,
  `type` varchar(15) DEFAULT NULL,
  `teacher` bit(1) DEFAULT NULL,
  `specialEd` bit(1) DEFAULT NULL,
  `behavior` bit(1) DEFAULT NULL,
  `health` bit(1) DEFAULT NULL,
  `advisor` bit(1) DEFAULT NULL,
  `supervisor` bit(1) DEFAULT NULL,
  `foodservice` bit(1) DEFAULT NULL,
  `finance` bit(1) NOT NULL,
  `responseApprover` bit(1) NOT NULL,
  `departmentID` int DEFAULT NULL,
  `schoolID` int NOT NULL,
  `schoolName` varchar(50) DEFAULT NULL,
  `schoolNumber` varchar(7) DEFAULT NULL,
  `departmentName` varchar(50) DEFAULT NULL,
  `excludeReferral` bit(1) DEFAULT NULL,
  `counselor` bit(1) DEFAULT NULL,
  `primaryTeachingArea` varchar(10) DEFAULT NULL,
  `assignmentCode` varchar(6) DEFAULT NULL,
  `healthLicense` varchar(15) DEFAULT NULL,
  `activity` bit(1) NOT NULL,
  `activityPreapprover` bit(1) NOT NULL
) ENGINE=InnoDB ;







-- skyline_staging.individual_view definition

CREATE TABLE `individual_view` (
  `personID` int NOT NULL,
  `stateID` varchar(15) DEFAULT NULL,
  `studentNumber` varchar(15) DEFAULT NULL,
  `staffNumber` varchar(15) DEFAULT NULL,
  `staffStateID` varchar(20) DEFAULT NULL,
  `geographicStaffStateID` varchar(20) DEFAULT NULL,
  `personGUID` char(36) DEFAULT NULL,
  `otherID` varchar(15) DEFAULT NULL,
  `additionalID` varchar(25) DEFAULT NULL,
  `edFiID` varchar(20) DEFAULT NULL,
  `identityID` int NOT NULL,
  `effectiveDate` date DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `middleName` varchar(50) DEFAULT NULL,
  `suffix` varchar(50) DEFAULT NULL,
  `alias` varchar(50) DEFAULT NULL,
  `gender` char(1) DEFAULT NULL,
  `birthdate` date DEFAULT NULL,
  `ssn` varchar(9) DEFAULT NULL,
  `legalFirstName` varchar(50) DEFAULT NULL,
  `legalLastName` varchar(50) DEFAULT NULL,
  `legalMiddleName` varchar(50) DEFAULT NULL,
  `legalSuffix` varchar(50) DEFAULT NULL,
  `legalGender` char(1) DEFAULT NULL,
  `raceEthnicity` varchar(3) DEFAULT NULL,
  `homePrimaryLanguage` varchar(5) DEFAULT NULL,
  `languageAlt` varchar(5) DEFAULT NULL,
  `languageAlt2` varchar(5) DEFAULT NULL,
  `districtID` int NOT NULL,
  PRIMARY KEY (`personID`)
) ENGINE=InnoDB ;
